#!/bin/bash

# Research Kickstart Script - Hybrid Evolution System
# Usage: ./research-kickstart.sh [project-name] [domain]

PROJECT_NAME=${1:-$(basename "$PWD")}
DOMAIN=${2:-"general"}

echo "🔬 Initializing business research for $PROJECT_NAME ($DOMAIN domain)..."

# Create research directory if it doesn't exist
mkdir -p research

# Generate market analysis template
cat > research/market-analysis.md << EOF
# Market Analysis - $PROJECT_NAME

## Executive Summary
[2-3 sentence summary of market opportunity and key findings]

## Market Size & Opportunity
- **Total Addressable Market (TAM)**: \$[X] billion
- **Serviceable Addressable Market (SAM)**: \$[X] billion  
- **Serviceable Obtainable Market (SOM)**: \$[X] million
- **Market Growth Rate**: [X]% CAGR (20XX-20XX)

## Target Market Analysis

### Primary Target Segment
- **Demographics**: [Age, income, location, etc.]
- **Psychographics**: [Behaviors, preferences, pain points]
- **Market Size**: [Number of potential users/customers]
- **Willingness to Pay**: \$[X] per [unit/month/year]

### Secondary Target Segments
- **Segment 2**: [Description and sizing]
- **Segment 3**: [Description and sizing]

## Problem Validation
- **Core Problem**: [Specific problem your solution addresses]
- **Problem Severity**: [How painful is this problem? 1-10 scale]
- **Current Solutions**: [How do people solve this today?]
- **Solution Gaps**: [What's missing from current solutions?]

## Market Trends
- **Technology Trends**: [Relevant tech developments]
- **Behavioral Trends**: [How user behavior is changing]
- **Industry Trends**: [Sector-specific developments]
- **Regulatory Trends**: [Compliance/legal considerations]

## Success Metrics
- [ ] Market size validated with credible sources
- [ ] Target segments clearly defined and sized
- [ ] Problem severity confirmed through research
- [ ] Competitive gaps identified and validated

---
*Generated by Hybrid Evolution System*
EOF

# Generate competitive analysis template
cat > research/competitive-analysis.md << EOF
# Competitive Analysis - $PROJECT_NAME

## Competitive Landscape Overview
[Brief summary of competitive environment and positioning]

## Direct Competitors

### Competitor 1: [Name]
- **Business Model**: [How they make money]
- **Market Position**: [Market share, funding, size]
- **Strengths**: [What they do well]
- **Weaknesses**: [Where they fall short]
- **Pricing**: [Pricing model and costs]
- **Technology Stack**: [If known/relevant]

### Competitor 2: [Name]
- **Business Model**: [How they make money]
- **Market Position**: [Market share, funding, size]
- **Strengths**: [What they do well]
- **Weaknesses**: [Where they fall short]
- **Pricing**: [Pricing model and costs]
- **Technology Stack**: [If known/relevant]

## Indirect Competitors & Alternatives
- **Alternative 1**: [Description and why users might choose this]
- **Alternative 2**: [Description and why users might choose this]
- **Alternative 3**: [Description and why users might choose this]

## Competitive Advantages
- **Unique Value Proposition**: [What makes you different/better]
- **Technical Differentiators**: [Technology advantages]
- **Market Differentiators**: [Go-to-market advantages]
- **Execution Differentiators**: [Team/resource advantages]

## Market Positioning
- **Category**: [How you'll position in the market]
- **Key Messages**: [Core marketing messages]
- **Target Positioning**: [Against specific competitors]

## Competitive Strategy
- **Short-term**: [6-month competitive strategy]
- **Medium-term**: [1-2 year strategy]
- **Long-term**: [2+ year strategy]

## Success Metrics
- [ ] All major competitors identified and analyzed
- [ ] Competitive advantages clearly articulated
- [ ] Market positioning strategy defined
- [ ] Competitive threats and opportunities mapped

---
*Generated by Hybrid Evolution System*
EOF

# Generate revenue model template
cat > research/revenue-model.md << EOF
# Revenue Model Analysis - $PROJECT_NAME

## Business Model Overview
[High-level description of how the business creates and captures value]

## Revenue Streams

### Primary Revenue Stream
- **Model**: [Subscription/Transaction/Advertising/etc.]
- **Pricing**: \$[X] per [unit/month/user/transaction]
- **Target Volume**: [Number of customers/transactions]
- **Projected Revenue**: \$[X] per month/year

### Secondary Revenue Streams
- **Stream 2**: [Description, pricing, volume, revenue]
- **Stream 3**: [Description, pricing, volume, revenue]

## Pricing Strategy
- **Pricing Model**: [Freemium/Tiered/Usage-based/etc.]
- **Price Points**: [Specific pricing tiers]
- **Competitive Pricing**: [How you compare to competitors]
- **Price Sensitivity**: [How sensitive is your market to pricing?]

## Unit Economics
- **Customer Acquisition Cost (CAC)**: \$[X]
- **Customer Lifetime Value (CLV)**: \$[X]
- **CLV/CAC Ratio**: [X]:1
- **Gross Margin**: [X]%
- **Contribution Margin**: [X]%

## Financial Projections

### Year 1
- **Revenue Target**: \$[X]
- **Customer Target**: [X] customers
- **Break-even**: Month [X]

### Year 2-3
- **Revenue Growth**: [X]% year-over-year
- **Market Expansion**: [New segments/geographies]
- **Profitability Target**: [X]% net margin

## Risk Assessment
- **Revenue Concentration Risk**: [How dependent on single revenue stream?]
- **Market Risk**: [How sensitive to market changes?]
- **Competitive Risk**: [Threat of price competition]
- **Execution Risk**: [Challenges in achieving targets]

## Success Metrics
- [ ] Revenue model validated with market research
- [ ] Unit economics show positive CLV/CAC
- [ ] Pricing strategy competitive and sustainable
- [ ] Financial projections realistic and achievable

---
*Generated by Hybrid Evolution System*
EOF

# Make scripts executable
chmod +x research-kickstart.sh

echo "✅ Research templates created successfully!"
echo "📁 Files created:"
echo "   - research/market-analysis.md"
echo "   - research/competitive-analysis.md"
echo "   - research/revenue-model.md"
echo ""
echo "📝 Next steps:"
echo "1. Fill out market analysis with specific research"
echo "2. Complete competitive analysis for your domain"
echo "3. Validate revenue model with target customers"
echo "4. Update templates as you gather more data"
echo "5. Use findings to inform technical development priorities"